
INSERT INTO `person` (first_name, last_name, address, gender, enabled) VALUES ('Derry', 'Brogini', '11th Floor', 'Male', b'0'),
 ('Bennie', 'Darridon', 'Apt 1753', 'Female', b'1'),
 ('Perren', 'Sellen', '7th Floor', 'Male', b'1'),
 ('Gates', 'Wickersley', 'Room 99', 'Female', b'0'),
 ('Wilmar', 'Pattington', 'Suite 75', 'Male', b'1'),
 ('Austen', 'Fowkes', '15th Floor', 'Male', b'1'),
 ('Conan', 'Hachette', '5th Floor', 'Male', b'1'),
 ('Vittoria', 'Eyrl', '18th Floor', 'Female', b'0'),
 ('Sherman', 'Tancock', 'Apt 1289', 'Male', b'0'),
 ('Wheeler', 'MacIlraith', 'Room 1340', 'Male', b'1'),
 ('Hebert', 'Ducker', 'PO Box 66352', 'Male', b'1'),
 ('Darb', 'Jakuszewski', '2nd Floor', 'Male', b'0'),
 ('Jorgan', 'Ruos', 'Room 1860', 'Male', b'0'),
 ('Shela', 'Darrington', '14th Floor', 'Female', b'0'),
 ('Pauly', 'Diter', 'PO Box 25372', 'Male', b'0'),
 ('Sonja', 'Crewdson', '1st Floor', 'Female', b'1'),
 ('Jervis', 'Wanell', '4th Floor', 'Male', b'1'),
 ('Merlina', 'Sillick', 'Room 625', 'Female', b'0'),
 ('Nari', 'Beebee', '19th Floor', 'Female', b'1'),
 ('Susanetta', 'Ruecastle', '12th Floor', 'Female', b'1'),
 ('Seward', 'Kittman', 'Apt 629', 'Male', b'0'),
 ('Nelson', 'Tourry', 'Room 1041', 'Male', b'0'),
 ('Maisey', 'Pflieger', 'Room 465', 'Female', b'0'),
 ('Bob', 'Goodread', 'Room 465', 'Male', b'1'),
 ('Arturo', 'Iacobacci', 'Room 1772', 'Male', b'0'),
 ('Neall', 'Hubbis', '5th Floor', 'Male', b'0'),
 ('Luise', 'Nettle', 'Room 1651', 'Female', b'1'),
 ('Jen', 'Ficken', 'PO Box 45562', 'Female', b'1'),
 ('Nickolai', 'Daughtrey', '8th Floor', 'Male', b'0'),
 ('Crystal', 'Reggiani', 'PO Box 99967', 'Female', b'0'),
 ('Aurore', 'Rope', 'Apt 1505', 'Female', b'0'),
 ('Brew', 'Hamblett', 'Room 912', 'Male', b'0'),
 ('Stevana', 'Giotto', 'PO Box 80606', 'Female', b'0'),
 ('Jacinta', 'Corke', 'Suite 81', 'Female', b'0'),
 ('Gerri', 'Venner', 'Apt 1158', 'Female', b'1'),
 ('Reinold', 'Dabs', 'Room 31', 'Male', b'1'),
 ('Shae', 'Damper', 'PO Box 32661', 'Male', b'0'),
 ('Eudora', 'Grew', 'Apt 1028', 'Female', b'0'),
 ('Jacinda', 'Gregersen', '1st Floor', 'Female', b'1'),
 ('Chelsie', 'Cargill', 'Room 1626', 'Female', b'1'),
 ('Skipper', 'Foxwell', 'Suite 78', 'Male', b'1'),
 ('Rourke', 'Jozwik', '3rd Floor', 'Male', b'0'),
 ('Portia', 'Towhey', 'Room 1909', 'Female', b'1'),
 ('Marv', 'Sperring', 'PO Box 59102', 'Male', b'0'),
 ('Woody', 'Este', 'Suite 94', 'Male', b'0'),
 ('Correy', 'De Minico', '7th Floor', 'Male', b'0'),
 ('Alix', 'Breffit', 'Room 584', 'Female', b'0'),
 ('Vania', 'Luesley', '12th Floor', 'Female', b'1'),
 ('Cob', 'Smelley', '3rd Floor', 'Male', b'0'),
 ('Jarad', 'Bexon', 'Room 779', 'Male', b'0'),
 ('Jobey', 'Abram', 'Room 498', 'Female', b'0'),
 ('Rosabella', 'Jacquet', 'PO Box 40831', 'Female', b'0'),
 ('Kalila', 'Kunz', 'PO Box 27980', 'Female', b'0'),
 ('Wilhelm', 'Vouls', 'Suite 16', 'Male', b'1'),
 ('Camilla', 'Adrian', 'Apt 1140', 'Female', b'0'),
 ('Jackson', 'Jahnig', 'Room 491', 'Male', b'0'),
 ('Averyl', 'Sibille', 'Suite 8', 'Female', b'1'),
 ('Emilee', 'Cossem', 'Suite 77', 'Female', b'0'),
 ('Mel', 'Eddies', '13th Floor', 'Female', b'1'),
 ('Garwin', 'Duffer', 'Suite 84', 'Male', b'1'),
 ('Freida', 'Coe', 'Apt 994', 'Female', b'1'),
 ('Dannel', 'Snugg', 'Room 1636', 'Male', b'1'),
 ('Norrie', 'Caulket', 'Room 1465', 'Female', b'1'),
 ('Angus', 'Lantiff', 'Suite 67', 'Male', b'1'),
 ('Randal', 'Bukowski', 'PO Box 91262', 'Male', b'0'),
 ('Adeline', 'Haskins', 'Apt 604', 'Female', b'1'),
 ('Aldous', 'Brusin', 'Suite 57', 'Male', b'0'),
 ('Gilda', 'Petrakov', 'Apt 398', 'Female', b'1'),
 ('Barde', 'Trustrie', 'Room 242', 'Male', b'1'),
 ('Brice', 'Grafham', 'Suite 77', 'Male', b'0'),
 ('Boniface', 'Adnam', 'Suite 45', 'Male', b'1'),
 ('Feodora', 'Yancey', '15th Floor', 'Female', b'0'),
 ('Nellie', 'Lawleff', 'PO Box 55384', 'Female', b'0'),
 ('Livvy', 'Titterell', 'Suite 35', 'Female', b'0'),
 ('Davine', 'Jurca', 'Apt 863', 'Female', b'0'),
 ('Emmi', 'O''Roan', 'Apt 1381', 'Female', b'0'),
 ('Ilyssa', 'Lipson', 'Apt 1626', 'Female', b'0'),
 ('Melonie', 'Sitlinton', 'PO Box 21863', 'Female', b'1'),
 ('Cesya', 'Holliar', 'PO Box 62525', 'Female', b'0'),
 ('Nicholas', 'Uttley', '10th Floor', 'Male', b'1'),
 ('Corissa', 'Blackman', 'PO Box 66120', 'Female', b'1'),
 ('Latrena', 'Dutson', 'Apt 1441', 'Female', b'1'),
 ('Sander', 'Baton', 'Room 1439', 'Male', b'0'),
 ('Pren', 'Son', '11th Floor', 'Male', b'0'),
 ('Devon', 'Boots', '18th Floor', 'Female', b'0'),
 ('Dacie', 'Shwenn', 'Apt 1764', 'Female', b'1'),
 ('Jock', 'Brocking', 'PO Box 53832', 'Male', b'0'),
 ('Lindsay', 'Yea', 'Room 90', 'Male', b'1'),
 ('Astrix', 'Muge', 'Room 1521', 'Female', b'1'),
 ('Fonzie', 'MacAlpine', 'Suite 42', 'Male', b'1'),
 ('Christie', 'Bater', 'Apt 480', 'Female', b'1'),
 ('Jabez', 'Westhoff', 'PO Box 59064', 'Male', b'1'),
 ('Edmon', 'Jouannin', 'PO Box 51595', 'Male', b'0'),
 ('Evangelina', 'Capstick', '17th Floor', 'Female', b'1'),
 ('Shae', 'Brunon', '8th Floor', 'Male', b'1'),
 ('Daniella', 'Purshouse', 'Room 1873', 'Female', b'1'),
 ('Cecile', 'Kindleysides', '17th Floor', 'Female', b'0'),
 ('Leodora', 'Goeff', '7th Floor', 'Female', b'1'),
 ('Farris', 'Spinella', 'PO Box 42840', 'Male', b'0'),
 ('Nobie', 'Asif', 'Apt 902', 'Male', b'0');

